
apiVersion: v1
kind: ServiceAccount
metadata:
 name: kube-sys-listpods
 namespace: default
 
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-sys-listpods
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-sys-listpods
subjects:
- kind: ServiceAccount
  name: kube-sys-listpods
  namespace: default
roleRef:
  kind: ClusterRole
  name: kube-sys-listpods
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod
metadata:
  name: kanister-listpods
  namespace: default
spec:
  containers:
  - name: kanister
    image: kanisterio/kanister-kubectl:1.18
  serviceAccountName: kube-sys-listpods

# kubectl -n kube-system get po 


# Which flag in the API Server specifies the authorization mechanism for your kubernetes cluster.
# authorization-mode

# What is default service account and where/how it is mounted on a pod in a namespace.
# when namespace is created service account with name default is created automatically. It is mounted as a vol inside container at location
# /var/run/secrets/kubernetes.io/serviceaccount/
