#  Deploy a pod with two containers, 
# one container should write some data (date let's say) to the volume and
# another container should read that data from volume and display it.



apiVersion: v1
kind: Pod
metadata:
  name: shared-vol-demo
  namespace: default
spec:
  containers:
  - name: nginx1
    image: nginx
    volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
    command: ['sh', '-c', "for run in $(seq 1 10); do date> /etc/foo/data.txt; sleep 2; done"]

  - name: nginx2
    image: nginx
    volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
    command: ['sh', '-c', "sleep 5; for run in $(seq 1 10); do  cat /etc/foo/data.txt; sleep 4; done"]

  volumes:
    - name: foo
      emptyDir: {}

    