apiVersion: v1
kind: Secret
metadata:
  name: postgresql
data:
  POSTGRES_PASSWORD: cGFzc3cwcmQxMjM=
  POSTGRES_DB: Ym9va3M=
  POSTGRES_USER: Ym9va3N1c2Vy
  PGDATA: L3Zhci9saWIvcG9zdGdyZXNxbC9kYXRhL3BnZGF0YQ==