apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  labels:
    app: postgres
data:
  POSTGRES_USER: booksuser
  POSTGRES_PASSWORD: p@ssw0rd123
  POSTGRES_DB: books
  PGDATA: /var/lib/postgresql/data/pgdata